### PR TITLE
WMSID: 6661

### PR DESCRIPTION
**Pull request by ibalasun**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by ibalasun** [comment]
Update to OIRI workshop : images have been changed from firefox to chrome

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask someone listed as the workshop team to add you?

**Review by rfontcha — DISMISSED** [review]
Please merge

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. There is a workshop #6661 (Oracle Identity Role Intelligence (OIRI) Workshop) in WMS that points to the path of the workshop you are updating. The #9762 workshop does not have a LiveLabs publishing entry. Could you please confirm that you are actually updating #6661?
2. Images’ names should be descriptive instead of step numbers
3. All images should have descriptive alternative texts in the Markdown files for accessibility
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by rfontcha** [comment]
Confirmed. PR is for #6661 and not 9762 
@ibalasun please address the remaining items from @arabellayao request above

**Comment by madhusudhanrao-ppm** [comment]
Please remove .DS hidden files

image

**Comment by arabellayao** [comment]
Hi! I am closing this PR now. Please fix the following issues suggested by Madhu and me, and create a new PR when you finish the changes.
1. Please remove .DS hidden files
2. Images’ names should be descriptive instead of step numbers
3. All images should have descriptive alternative texts in the Markdown files for accessibility
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Pull request closed without merging**
