### PR TITLE
feat: Add OCI Network Firewall Workshop (#WMS 11288)

### PR DESCRIPTION
**Pull request by apooniajjn**
# Add here your WMS ID

- OCI Network Firewall: **11288**

Below details applies for **OCI Network Firewall**. Changes include detailed instructions, automation, manual steps, additional information and PAR URLs. 

# General requirements
1. Information in the workshop is adequate and updated - **Yes**
2. Code is correct and working - **Yes**
3. Links are correct - **Yes**
4. Make sure you enter the help email link in your manifest.json - **Yes**
5. Please make sure WMS URLs are updated as needed after your PR is approved - **Yes**

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive * 
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html 
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
Image tags should have alt text / alternate text 
image

**Comment by apooniajjn** [comment]
Thanks @madhusudhanrao-ppm  I have included requested Alternative Text and merged to my branch (rebased) . Please check.

**Review by anooshapilli — CHANGES_REQUESTED** [review]
@apooniajjn - We do not use branching. Could you make sure all the content is on the main branch? 
Please submit the filled out  [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/mQVboV9nECbPbq4RYZofjCFkQRZD1FJk_RkLC8_Wut5wDtxh5s0Tu2_x5BklCdRa/n/c4u04/b/self-qa-form/o/qa-form/QA.docx) to your stakeholder mailbox - [livelabs-help-oci_us@oracle.com](mailto:livelabs-help-oci_us@oracle.com) for review.

**Comment by apooniajjn** [comment]
Thank you @anooshapilli  let me use **main** branch of my forked repo and I will open a new PR.

**Pull request closed without merging**
