### PR TITLE
New Data Redaction lab and minor updates to existing labs

### PR DESCRIPTION
**Pull request by richardcevans**
# Add here your WMS ID

WMS ID: 11318: Protect sensitive data in REST GET calls using Oracle Data Redaction
WMS ID: 7641: Prevent unauthorized data access in Autonomous Databases with Database Vault
WMS ID:  11744: Oracle Data Redaction for Oracle Autonomous Database

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [ x] Filenames are descriptive
- [ x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by carmenberdant1 — CHANGES_REQUESTED** [review]
Hi @richardcevans, these images need to have the private information blurred:
- autonomous-db/common/prepare-setup/images/adb-set_003a.png
- autonomous-db/common/prepare-setup/images/adb-set_004a.png
- autonomous-db/data-redaction/images/adb-dr_061a.png
- autonomous-db/dbvault/images/adb-dbv_007.png
- autonomous-db/protect-sensitive-data-in-rest-get-calls-using-oracle-data-redaction/configure-the-autonomous-database-environment/images/select-import-image.png
- autonomous-db/protect-sensitive-data-in-rest-get-calls-using-oracle-data-redaction/configure-the-autonomous-database-environment/images/ssh-into-instance.png
These files have the wrong numbering to some tasks: 
- autonomous-db/data-redaction/data-redaction.md - wrong numbering Task 2
- autonomous-db/protect-sensitive-data-in-rest-get-calls-using-oracle-data-redaction/use-redaction-anonymize-all-restcalls-and-queries/use-redaction-anonymize-all-restcalls-and-queries.md - Task 1

**Comment by carmenberdant1** [comment]
@richardcevans, please resolve the branch out-of-date issue

**Review by richardcevans — COMMENTED** [review]
updated images to obfuscate information

**Review by anacoman11 — COMMENTED** [review]
Hi @richardcevans, sent you a DM

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @richardcevans, please make sure that all images filenames are lowercase from autonomous-db/protect-sensitive-data-in-rest-get-calls-using-oracle-data-redaction/reset-your-environment/images/

**Review by anacoman11 — APPROVED** [review]

**Review by carmenberdant1 — APPROVED** [review]

**Pull request merged**
