### PR TITLE
[Story of a Hack] Final release - WMS ID 11105

### PR DESCRIPTION
**Pull request by hloumi**
Hi team,

According to the feedback from Rene, Meghana and Anoosha, here is the final version of my new lab :-)

Could you please apply theses changes to Prod and let me know?

Thanks in advance.

Best regards
Hakim

### CODE REVIEW

**Comment by madhusudhanrao-ppm** [comment]
please provide WMS ID and the image names should be self-descriptive

image

**Review by rfontcha — APPROVED** [review]
Please merge once the changes requested are made.
@hloumi - Address the request above, name the files accordingly, and commit. Once the PR is merged, proceed to update WMS with the correct URLs

**Review by rfontcha — CHANGES_REQUESTED** [review]
@hloumi - Please address the request made by @madhusudhanrao-ppm

**Comment by madhusudhanrao-ppm** [comment]
Please provide descriptive image names for example this image can be employee-search.png instead of hack-lab3d-05.png
 
 
image

**Review by madhusudhanrao-ppm — APPROVED** [review]
Hakim will rename images at a later time.

**Pull request merged**
