### PR TITLE
WMS ID: #11460

### PR DESCRIPTION
**Pull request by stephenstuart17**
WMS ID: #11460

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ x] All filenames are lower case (including folders, images, files, etc.)
- [ x] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by stephenstuart17** [comment]
This is a PR for 2 LiveLabs- WMS ID #11460 and #11463. Ping me if there's any questions. Thank you!

**Review by ramumg — CHANGES_REQUESTED** [review]
Hi @stephenstuart17, 

The names of your images should be more descriptive not step numbers. We can approve the request whenever this change is made. 

Thank you, 
Ramu

**Comment by klazarz** [comment]
@stephenstuart17 we can accept the filenames but the alternate image descriptions need to be updated as they are the same within a markdown. For example, VPD <-- [VPD] is used across all image tags in this file. This is not an appropriate alternative image description to be conform with Oracle's Accessibility Guidelines

**Comment by stephenstuart17** [comment]
Hi Ramu and Kevin, 

I just got done updating the image names and pushed them. Once these have gone through, I will submit another PR. 

Thank you! 

-Stephen Stuart

**Comment by stephenstuart17** [comment]
The changes have been committed and gone through. It's not letting me submit another PR, just says "View Pull Request" in the top right. Let me know if anything else needs to be done on my end. 

Thanks, 

Stephen Stuart

**Comment by klazarz** [comment]
@stephenstuart17 the image names are fine. but the alternate image descriptions are violating Oracle's Accessibility Guidelines:
VPD

[VPD] is used in all image tags. Simliar for the proxy lab [Proxy] is used across all images tags.
Alternate image descriptions are contained in [].

**Comment by stephenstuart17** [comment]
Hey Kevin, 

I updated the alternate image descriptions and just pushed the changes. They should go through in 15-20 mins. 

Thanks, 

Stephen

**Comment by anooshapilli** [comment]
@stephenstuart17 - I see the workshop is In Development status in WMS. Please review the workshop using the self QA Checklist in WMS, make necessary changes to the workshop, and update the status to Self QA Complete in WMS.

**Comment by anooshapilli** [comment]
@stephenstuart17 - Just following up on the above request.

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
