### PR TITLE
WMS ID: 11445 - OAS SSO With IAM Domain via App Gateway

### PR DESCRIPTION
**Pull request by stakk55**
First Version

# WMS ID: 11445

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by stakk55** [comment]
Please reach out to Chetan.soni@oracle.com and sagar.takkar@oracle.com for any queries. This live lab needs to be published asap, as it is already delayed due to code freeze.

**Comment by anooshapilli** [comment]
Hi @stakk55 - Please update the workshop status to Self QA Complete in WMS after performing the self QA of the workshop to be able to review and and approve this PR.

**Comment by stakk55** [comment]
I have completed the same, please check and let me know if anything is pending from my end.

**Review by anooshapilli — COMMENTED** [review]
@stakk55 - Please make these changes to the PR

Please rename the image titles to lowercase 
image

You can leverage the get started from common repo instead of creating a new folder and content - https://github.com/oracle-livelabs/common/tree/main/labs/cloud-login

rename the freetier folder to sandbox if needed or you can delete that folder - 
image

**Comment by stakk55** [comment]
Required changes are done, please let me know the next step from my side.

**Review by stevenlemme — COMMENTED** [review]
As directed by stakk55 message sent in WMS to contacts as directed to update the WMS as directed so request can move along in the process

**Comment by anooshapilli** [comment]
@stakk55 - Please rename the images and the file name to lowercase and delete Get started folder if not needed to approve the approve.
image

**Comment by stakk55** [comment]
Self QA is completed. And suggested changes are done to rename the folder and We need the Get started folder as well.

**Comment by anooshapilli** [comment]
@stakk55 - Contacted over slack

**Pull request merged**
