### PR TITLE
WMS ID #11394

### PR DESCRIPTION
**Pull request by secassessment**
# WMS ID: 11394

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@secassessment - please make these changes to the workshop

- Please remove the Lab X - in the lab titles in the markdown.
- Remove Lab from Estimated Lab Time in the labs
- For Get Started lab you can use the common lab link in manifest.json file - https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md and for Need Help lab you can use this link - https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md
- Please delete the lab folders and files
image
image
image

**Comment by secassessment** [comment]
Hi,

I did all changes you asked me to do, except for the files https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md and  https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md. Please take into account that this is a workshop only used for Oracle Cloud World, and we will use a different environment and cloud login. I removed the tenancy, desktop and sandbox options in the manifest file. We will only have ocw23 tenancy option for this, and will not publish as public, but Event type workshop.

**Review by ZRTalke — DISMISSED** [review]
Hi @secassessment 

Please fill out the learn more & acknowledgements section of the hsm-ksm-setup md file and add the proper you may now proceed to the next lab lines to your labs

image

**Comment by secassessment** [comment]
Hi, I have removed that file. It was not needed.

**Review by klazarz — APPROVED** [review]

**Review by klazarz — APPROVED** [review]

**Pull request merged**
