### PR TITLE
WMS 11271 - Securing a legacy application using Oracle Database Vault on Oracle Autonomous Database

### PR DESCRIPTION
**Pull request by ethan-shmargad**
# WMS 11271

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Checked ] All filenames are lower case (including folders, images, files, etc.)
- [ Checked] Filenames are descriptive
- [ Checked] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ Checked] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Checked ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Use this file as the "Get Started" lab for desktop/manifest.json: "https://oracle-livelabs.github.io/common/labs/remote-desktop/using-novnc-remote-desktop.md"
2. Use this file as the "Need Help?" lab for freetier/manifest.json: "https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier.md" 
Thanks!

**Comment by ethan-shmargad** [comment]
Ok made those changes! Let me know if you need anything else

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! You only need one of the "freetier" and "tenancy" folders, since they both provide instructions for running on customer's tenancies. The "Need Help" lab should be "https://oracle-livelabs.github.io/common/labs/need-help/need-help-freetier". Please refer to files here (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops) to see what common labs you need to use for the "Get Started" and "Need Help" labs for different manifest.json files. Thanks!

**Comment by ethan-shmargad** [comment]
Ok I believe I made the right adjustments. Added some changes to the introduction as well.  Let me know if something still needs to be fixed

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
