### PR TITLE
ID#11456 - Oracle Access Governance - Administration 

### PR DESCRIPTION
**Pull request by anbuoracle**
ID#11456 - Oracle Access Governance - Administration 

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by KillianLynch — COMMENTED** [review]
Hi @anbuoracle, Would you please update your development URL in WMS to reflect the development environment.

**Comment by anbuoracle** [comment]
I have updated the dev URL.



Thanks
Anbu

From: KillianLynch ***@***.***>
Date: Friday, July 28, 2023 at 4:47 PM
To: oracle-livelabs/security ***@***.***>
Cc: Anbu Anbarasu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/security] ID#11456 - Oracle Access Governance - Administration (PR #114)

@KillianLynch commented on this pull request.

Hi @anbuoracle<https://urldefense.com/v3/__https:/github.com/anbuoracle__;!!ACWV5N9M2RV99hQ!MNVDYw_t-5TgVgj5cxzII-NOV1RFf-yipcpX-EAqQ0mdSqlpetq0OT64kWo7EKAslhVeHtJ7ttQ6b8fBNKE8YUqtq0c$>, Would you please update your development URL in WMS to reflect the new workshop OCW file

**Comment by anbuoracle** [comment]
Killian, It’s updated. Can you please approve the PR?



Thanks
Anbu

From: KillianLynch ***@***.***>
Date: Friday, July 28, 2023 at 4:47 PM
To: oracle-livelabs/security ***@***.***>
Cc: Anbu Anbarasu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/security] ID#11456 - Oracle Access Governance - Administration (PR #114)

@KillianLynch commented on this pull request.

Hi @anbuoracle<https://urldefense.com/v3/__https:/github.com/anbuoracle__;!!ACWV5N9M2RV99hQ!MNVDYw_t-5TgVgj5cxzII-NOV1RFf-yipcpX-EAqQ0mdSqlpetq0OT64kWo7EKAslhVeHtJ7ttQ6b8fBNKE8YUqtq0c$>, Would you please update your development URL in WMS to reflect the new workshop OCW file

**Review by anooshapilli — APPROVED** [review]

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @anbuoracle 

I'm reviewing your pull request and noticed a few areas that need to be updated:

- It looks like your pull request is editing two workshops. Please provide the second WMS ID or remove the changes to the workshop that is not accessgovernance-admin
- In the agent-install images folder and connect-oig-odb the "env_setup" images use _ which need to be changed to - to comply with naming guidelines. Please review the files to makes sure this isn't occurring in any other locations
- In the aginstance-cleanup images folder please update the images titled Screenshot to names fitting the naming guidelines
- I checked the WMS entry and the development url still needs to be properly updated. It looks like a github.com url is currently there and this needs to be a github pages github.io address

Let me know if you have any questions. Thanks!

**Pull request merged**
