### PR TITLE
Documentation Updates : WMS ID - 9381

### PR DESCRIPTION
**Pull request by anuj-git1412**

### CODE REVIEW

**Review by arabellayao — DISMISSED** [review]
Hi! Did you copy the verify-compute folder from https://github.com/oracle-livelabs/common/tree/main/labs/verify-compute? If you want to use those labs directly, you can refer to them using absolute links link (e.g. https://oracle-livelabs.github.io/common/labs/verify-compute/verify-compute.md). If you want to update one lab and use your own version, please delete other md files that you do not use. Thanks!

**Comment by madhusudhanrao-ppm** [comment]
please refer QA checklist document in WMS, Public IP address and OCIDs need to masked / blurred

https://raw.githubusercontent.com/oracle-livelabs/security/9b8ba2a970bc3644137bb31c05294a27a3c02363/iam-containers/verify-compute/images/em-cloudshell.png

**Comment by anuj-git1412** [comment]
> Hi! Did you copy the verify-compute folder from https://github.com/oracle-livelabs/common/tree/main/labs/verify-compute? If you want to use those labs directly, you can refer to them using absolute links link (e.g. https://oracle-livelabs.github.io/common/labs/verify-compute/verify-compute.md). If you want to update one lab and use your own version, please delete other md files that you do not use. Thanks!

Removed the extra/unused md files.

**Comment by anuj-git1412** [comment]
> please refer QA checklist document in WMS, Public IP address and OCIDs need to masked / blurred
> 
> https://raw.githubusercontent.com/oracle-livelabs/security/9b8ba2a970bc3644137bb31c05294a27a3c02363/iam-containers/verify-compute/images/em-cloudshell.png

The concerned was an unused image. Removed that along with the other unused ones.

**Review by madhusudhanrao-ppm — APPROVED** [review]
Discussed with Anuj about the duplicate folder which needs to be updated in manifest.json

**Pull request merged**
