### PR TITLE
Get Started with Oracle Data Safe (#700)

### PR DESCRIPTION
**Pull request by joglover**
Updates for Cloud World

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues:
1. assess-database-users/images/run-scuript.txt should be placed under the files folder, not the images folder
2. workshops/ocw-freetier/manifest.json: the "Need Help" lab should point to the need-help-freetier.md file.
Thanks!

**Comment by joglover** [comment]
I have made the fixes requested.

**Comment by joglover** [comment]
Is there any way you can fix the paths in the manifest without me doing a pull request?

**Comment by arabellayao** [comment]
> Is there any way you can fix the paths in the manifest without me doing a pull request?

Hi Jody! You can stash the unfinished changes, so that they are not included in your PR. Or I can submit a PR to fix the issue with manifest.json - please let me know when your commits are ready to be pushed. Thank you!

**Comment by joglover** [comment]
Hi @arabellayao , would you please submit a PR to fixt the issue with the manifest.json? Thanks! In the meantime, I'm going to try and get the changes completed today/tomorrow.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
