### PR TITLE
 ID#11456 - Oracle Access Governance - Administration

### PR DESCRIPTION
**Pull request by anbuoracle**
ID#11456 - Oracle Access Governance - Administration
Initial Pull Request

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@anbuoracle - This workshop is in Approved status. Please review the workshop using the Self QA Checklist and update the workshop status to Self QA Complete in WMS to review this PR.

**Review by anooshapilli — COMMENTED** [review]
@anbuoracle - Please make these changes to the workshop
- In Introduction Lab, rename Estimated Time to Estimated Workshop Time
- In Lab 1, 3, 5, 8, 9, 10, 11, 12, 13 - rename Estimated Lab Time to Estimated Time
- In Lab 1, 5, 6, 7, 8, 9, 10, 11, 12, 13 - Fix the typo - Acknowledgements.
 - In Lab 2, 6, and 7 - move Estimated Time to be a separate line before objectives
 - In Lab 2 - number the instructions after Task 1 Step 2
 - In Lab 6 Task 4 -  indent the instructions with 4 spaces from the beginning of the line to fix the numbering

**Comment by anooshapilli** [comment]
@anbuoracle - In Lab 13, remove Lab from ETA and fix the typo to the correct spelling - "Acknowledgements" in the labs

**Comment by anbuoracle** [comment]
Closing this request. Will resubmit after another review.

**Pull request closed without merging**
