### PR TITLE
New LiveLab repository event for 3262.

### PR DESCRIPTION
**Pull request by kjlsinghoracle**
WMS ID: 3262

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by carmenberdant1 — DISMISSED** [review]
Hi @kjlsinghoracle, please change the name to the data-masking-subsetting-TTT24 folder in lowercase. Thank you!

**Comment by carmenberdant1** [comment]
@kjlsinghoracle please resolve your conflicts

**Comment by kjlsinghoracle** [comment]
I have made the name change and pushed it to fork. I can see the change locally but not on the github web.
Screenshot 2024-11-20 101250
Can you please verify if you can see at your end.

**Comment by kjlsinghoracle** [comment]
Just changed and pushed the changes back.

**Comment by carmenberdant1** [comment]
Hi @kjlsinghoracle, please resolve your conflicts. Thank you!

**Review by ramonamagadan18 — APPROVED** [review]

**Pull request merged**
