### PR TITLE
WMS ID: 11430, WMS ID: 11315, WMSID: 11496 

### PR DESCRIPTION
**Pull request by ibalasun**
# Add here your WMS ID
WMS ID: 11430, WMS ID: 11315, WMSID: 11496
# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by ibalasun** [comment]
Hi,

We are updating 3 livelabs - accessgovernance-access-controls, accessgovernance-oci-iam, accessgovernancee2e folders.

Thanks

**Comment by ramumg** [comment]
Hi @ibalasun, 

please create one pull request per WMS. 

Thank you!

**Comment by klazarz** [comment]
@ibalasun can you please update your Github profile with your real name for verification?

**Comment by ibalasun** [comment]
Hi @ramumg ,

In this pull request, We are looking to update all the 3 livelabs instructions simultaneously - accessgovernance-access-controls, accessgovernance-oci-iam, accessgovernancee2e folders. 


Kindly let us know more on how we could raise the pull request. 


Thanks

**Comment by ibalasun** [comment]
@klazarz 

Updated Github profile.

**Review by kaylien — APPROVED** [review]

**Pull request merged**
