### PR TITLE
WMS ID:6661 - Oracle Identity Role Intelligence (OIRI) Workshop

### PR DESCRIPTION
**Pull request by ibalasun**
Update to OIRI workshop : 

1) Images have been changed from firefox to chrome
2) Removed .DS hidden files
3) Images’ names  changed to descriptive instead of step numbers
4) All images have descriptive alternative texts in the Markdown files for accessibility

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Workshop #6661 points to security/oiri. Could you please keep you changes only to the oiri folder? 
Also, all images should have descriptive alternative texts in the Markdown files for accessibility.
Thanks!

**Comment by ibalasun** [comment]
Hi,

Update to OIRI workshop :

Removed .DS hidden files
All images have descriptive alternative texts in the Markdown files for accessibility

**Review by arabellayao — APPROVED** [review]

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! It seems you are changing other workshop folders that do not belong to you. Can you please make sure the PR only includes changes to the oiri folder? Thanks!
Screen Shot 2022-12-16 at 10 54 32 AM

**Comment by arabellayao** [comment]
Followed up with Indiradarshni on 12/20.

**Comment by arabellayao** [comment]
Hi! Please make sure the PR only includes changes to the oiri folder, and merge the latest changes from main into this branch. You can create a new PR after finish doing that. Thanks!

**Pull request closed without merging**
