### PR TITLE
ID#11430 - Oracle Access Governance with OCI IAM

### PR DESCRIPTION
**Pull request by anbuoracle**
ID#11430 - Oracle Access Governance with OCI IAM

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by william-masdon-oracle — DISMISSED** [review]
Hi @anbuoracle ,
I see you have 2 parent folders "accessgoverance-oci-iam" and "accessgovernancee2e" with a lot (if not all) of the same information. Why is this needed? If it isn't, please remove the unneeded folders.

**Comment by william-masdon-oracle** [comment]
Hi Anbu,
One workshop should only exist under one folder. If the changes are so significant that they require completely different folders, then I would suggest creating another workshop in WMS. Until then, your workshop shouldn't contain multiple versions unless those version are for our different deployment options (brown vs. green button).

**Comment by william-masdon-oracle** [comment]
Hi Anbu, 
I see, you are also updating WMS 11315. I'll approve the PR now. In the future please include the WMS IDs of all updated workshops when creating the PR.
Thanks,
William

**Review by william-masdon-oracle — APPROVED** [review]

**Comment by anbuoracle** [comment]
Will do. Thank you!



Thanks
Anbu

From: William Masdon ***@***.***>
Date: Tuesday, May 30, 2023 at 4:10 PM
To: oracle-livelabs/security ***@***.***>
Cc: Anbu Anbarasu ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/security] ID#11430 - Oracle Access Governance with OCI IAM (PR #91)

Hi Anbu,
I see, you are also updating WMS 11315. I'll approve the PR now. In the future please include the WMS IDs of all updated workshops when creating the PR.
Thanks,
William

**Pull request merged**
