### PR TITLE
Minor changes to enhance documentation

### PR DESCRIPTION
**Pull request by gautamm2707**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by anooshapilli** [comment]
@gautamm2707 - Please share the WMS ID for the workshop.

**Comment by anooshapilli** [comment]
@gautamm2707 - Following up on this PR

**Comment by gautamm2707** [comment]
Hi Anoosha,

WMS ID #11375

Regards,
Gautam M

From: Anoosha Pilli ***@***.***>
Date: Thursday, 11 May 2023 at 2:32 AM
To: oracle-livelabs/security ***@***.***>
Cc: Gautam Mishra ***@***.***>, Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/security] Minor changes to enhance documentation (PR #83)

@gautamm2707<https://urldefense.com/v3/__https:/github.com/gautamm2707__;!!ACWV5N9M2RV99hQ!MrYT1g_OQo-o9-lnB0mwKw3v4SheBfOacdDGTlrPX2bdmDoMf_xDTypHeU9VgfLxl9zR1VO56hlZubAYAzjJVOjNrkc$> - Following up on this PR

**Comment by gautamm2707** [comment]
Hi Anoosha,

Can you kindly approve the merge request.

Regards,
Gautam M

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
